@url_dev=http://localhost:3000/api/v1

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 94548133e47cc93c6ef963c1682ab30922bbc7f07dfdbb05d2837960acc354da

{
  "name": "shop Test",
  "email": "test@example.com",
  "password": "secret"
}